services:
  clv-project:
    build: .
    container_name: clv_project
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
      - ./models:/app/models
      - ./src:/app/src
      - ./report:/app/report
      - ./tests:/app/tests
    environment:
      - JUPYTER_TOKEN=clv2026
    restart: unless-stopped
